//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRegistrasiVaksin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Vaksin
    {
        public string no_register { get; set; }
        public System.DateTime tanggal_dibuat { get; set; }
    }
}
